---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-deployment
  labels:
    author: Nav
    type: proxyserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
       - name: mynginx
         image: nginx
         ports:
          - containerPort: 80
            hostPort: 8087
...
