---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    author: intelliqit
    type: proxyserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxyserver
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxyserver
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8888

...            
