---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: xyz
    author: abc
spec:
  containers:
    - name: mynginx
      image: nginxs
      ports:
        - containerPort: 80
          hostPort: 8888
...
