---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 labels:
  author: abc
spec:
 type: LoadBalancer
 ports:
   - targetPort: 80
     port: 80
 selector:
  type: CMS
  author: abc
...

  
