---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    author: naveen
spec:
  type: LoadBalancer
  ports:
    - targetPort: 2368
      port: 2368
  selector:
    type: CMS
    author: naveen
...
