---
apiVersion: v1
kind: Pod
metadata: 
 name: jenkin
 labels: 
  author: naveen
  type: proxy
spec:   
 containers:
  - name: myjenkin
    image: jenkins/jenkins
    ports:
      - containerPort: 8080
        hostPort: 8080

...
