---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-abc1
  labels:
    author: abc
    type: webserver
spec:
  replicas: 3
  template:
    metadata:
      name: tomcat-abc1
      labels:
        type: webserver
    spec:
      containers:
       - name: tomcat-abc1
         image: tomcat
         ports:
          - containerPort: 8080
            hostPort: 8086
...

