---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    author: preeti
    type: webserver
spec:
    replicas: 3
    template:
      metadata:
        name: httpd-pod
        labels:
          author: preeti
      spec:
       containers:
        - name: myhttpd
          image: httpd
          ports:
           - containerPort: 80
             hostPort: 8888
...       




