---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    author: abc
    type: webserver
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        author: abc
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
...
