---
apiVersion: v1
kind: Service
metadata:
  name: tomcat1
  labels:
    author: abc
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    author: abc
    type: webserver
...
