---
apiVersion: v1
kind: Service
metadata:
  name: nginxx3
  labels:
    author: abc
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      
  selector:
    type: ClusterIP
    author: abc
...
