
---
apiVersion: v1
kind: Service
metadata:
  name: httpd1
  labels:
    author: abc

spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:     
    author: abc
    type: ClusterIP
...
